### ISSUE TITLE
running this produce error: var format = parseFormat(1397418578);

### ISSUE THREAD

**Issue by idanb11** [gr2m/moment-parseformat#62]
```
var format = parseFormat(1397418578);

c:\Users\Idanb11\Work\workspace\node_modules\moment-parseformat\lib\parseformat.js:79
  format = format.replace(regexUnixMillisecondTimestamp, 'x')
                  ^

TypeError: format.replace is not a function
    at parseFormat (c:\Users\Idanb11\Work\workspace\node_modules\moment-parseformat\lib\parseformat.js:79:19)
    at Object.<anonymous> (c:\Users\Idanb11\Work\workspace\server.js:5:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by gr2m** [comment]
What would you expect `parseFormat(1397418578)` to return? I’d suggest it should throw a better error message than `format.replace`. Would happily accept a pull request for it, you can add a test case to https://github.com/gr2m/moment-parseformat/blob/master/test/moment-parseformat-test.js

**Comment by idanb11** [comment]
Hi @gr2m ,

I expect that parseFormat(1397418578) will not crash the program and return the value `X` - exactly like when you run parseFormat("1397418578").

parseFormat should be able to work with Numbers and Strings

**Comment by gr2m** [comment]
I think we can add an `input.toString()` there and then a check for the `x` format. I don’t need that so I won’t work on it, but if you send a pull request with a test, I’d be happy to help get it merged

**Comment by gr2m** [comment]
done via #64, released in https://github.com/gr2m/moment-parseformat/releases/tag/v2.2.0
